import type { Product, Recommendation, SalesRecord, MarketTrend, DashboardStats } from './types'
import { calcCost } from './calculations'

function makeProduct(
  id: string,
  name: string,
  category: string,
  sourcePlatform: Product['sourcePlatform'],
  sellPlatform: Product['sellPlatform'],
  buyPrice: number,
  sellPrice: number,
  purchaseShipping: number,
  velocity: Product['salesVelocity'],
  rank: number,
  reviewCount: number,
  rating: number,
  imageUrl: string,
  url: string
): Product {
  return {
    id,
    name,
    imageUrl,
    url,
    category,
    sourcePlatform,
    sellPlatform,
    cost: calcCost(buyPrice, sellPrice, sellPlatform, purchaseShipping),
    salesVelocity: velocity,
    rank,
    reviewCount,
    rating,
    lastUpdated: new Date().toISOString(),
  }
}

export const MOCK_PRODUCTS: Product[] = [
  makeProduct(
    'p1',
    'Nintendo Switch 本体 Joy-Con(L) ネオンブルー/(R) ネオンレッド HAC-S-KABAA',
    'ゲーム',
    'amazon', 'mercari',
    28500, 36000, 0,
    'high', 1, 45213, 4.6,
    'https://via.placeholder.com/200x200?text=Switch',
    'https://www.amazon.co.jp'
  ),
  makeProduct(
    'p2',
    'Apple AirPods Pro (第2世代) MagSafe充電ケース(USB-C)付き MTJV3J/A',
    '家電・オーディオ',
    'amazon', 'mercari',
    28000, 34500, 0,
    'high', 3, 89324, 4.8,
    'https://via.placeholder.com/200x200?text=AirPods',
    'https://www.amazon.co.jp'
  ),
  makeProduct(
    'p3',
    'ポケモンカードゲーム スカーレット&バイオレット 強化拡張パック 151 BOX',
    'トレカ',
    'rakuten', 'mercari',
    5500, 9200, 500,
    'high', 2, 21045, 4.9,
    'https://via.placeholder.com/200x200?text=Pokemon',
    'https://www.rakuten.co.jp'
  ),
  makeProduct(
    'p4',
    'LEGO テクニック 42151 ブガッティ ボライド',
    'おもちゃ・ホビー',
    'amazon', 'yahoo',
    15800, 22000, 0,
    'medium', 12, 12051, 4.7,
    'https://via.placeholder.com/200x200?text=LEGO',
    'https://www.amazon.co.jp'
  ),
  makeProduct(
    'p5',
    'ダイソン V15 Detect Absolute SV22 ABL コードレス掃除機',
    '家電',
    'rakuten', 'mercari',
    68000, 87000, 0,
    'medium', 8, 34561, 4.5,
    'https://via.placeholder.com/200x200?text=Dyson',
    'https://www.rakuten.co.jp'
  ),
  makeProduct(
    'p6',
    'ソニー WH-1000XM5 ワイヤレスノイズキャンセリングヘッドホン WH1000XM5B',
    'オーディオ',
    'amazon', 'mercari',
    32000, 41000, 0,
    'medium', 5, 56781, 4.6,
    'https://via.placeholder.com/200x200?text=Sony',
    'https://www.amazon.co.jp'
  ),
  makeProduct(
    'p7',
    'ワンピースカードゲーム 頂上決戦 OP02 BOX 24パック入り',
    'トレカ',
    'rakuten', 'mercari',
    4500, 8500, 500,
    'high', 4, 18734, 4.8,
    'https://via.placeholder.com/200x200?text=OnePiece',
    'https://www.rakuten.co.jp'
  ),
  makeProduct(
    'p8',
    'PlayStation 5 本体 CFI-2000A01 (ディスクドライブ搭載モデル)',
    'ゲーム',
    'amazon', 'mercari',
    66980, 74000, 0,
    'high', 2, 78432, 4.7,
    'https://via.placeholder.com/200x200?text=PS5',
    'https://www.amazon.co.jp'
  ),
]

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'r1',
    product: MOCK_PRODUCTS[2],
    reason: 'ポケモン151は生産調整の影響で品薄が続き、メルカリでの転売価格が安定して定価の1.5〜2倍推移。シングルカード需要も高くBOX購入後の小分け販売も有効。',
    confidence: 93,
    estimatedMonthlySales: 10,
    buyQuantity: 5,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r2',
    product: MOCK_PRODUCTS[0],
    reason: '年末商戦に向けてNintendo Switch本体の需要が急上昇。Amazonでの在庫が減少傾向にあり、価格上昇の兆候あり。今後1〜2週間が仕入れの好機。',
    confidence: 85,
    estimatedMonthlySales: 4,
    buyQuantity: 3,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r3',
    product: MOCK_PRODUCTS[6],
    reason: 'ワンピースカードの新弾発売直後で需要最高潮。楽天ポイント還元を考慮すると実質仕入れコストをさらに下げられる。',
    confidence: 88,
    estimatedMonthlySales: 8,
    buyQuantity: 4,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r4',
    product: MOCK_PRODUCTS[3],
    reason: 'LEGOテクニックシリーズは廃番後に価格が上昇する傾向。現在定価購入可能なうちに仕入れておくことを推奨。',
    confidence: 78,
    estimatedMonthlySales: 3,
    buyQuantity: 3,
    status: 'approved',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
]

export const MOCK_SALES: SalesRecord[] = [
  {
    id: 's1',
    productName: 'ポケモンカード 151 BOX',
    category: 'トレカ',
    buyPrice: 5500,
    sellPrice: 9200,
    quantity: 3,
    profit: 9240,
    profitRate: 56.0,
    platform: 'mercari',
    soldAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 's2',
    productName: 'Nintendo Switch Joy-Con ネオン',
    category: 'ゲーム',
    buyPrice: 28500,
    sellPrice: 36000,
    quantity: 1,
    profit: 3430,
    profitRate: 12.0,
    platform: 'mercari',
    soldAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 's3',
    productName: 'LEGO テクニック 42151',
    category: 'おもちゃ',
    buyPrice: 15800,
    sellPrice: 21500,
    quantity: 2,
    profit: 7240,
    profitRate: 22.9,
    platform: 'yahoo',
    soldAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 's4',
    productName: 'AirPods Pro 第2世代',
    category: '家電',
    buyPrice: 28000,
    sellPrice: 34500,
    quantity: 1,
    profit: 2950,
    profitRate: 10.5,
    platform: 'mercari',
    soldAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 's5',
    productName: 'ワンピースカード 頂上決戦 BOX',
    category: 'トレカ',
    buyPrice: 4500,
    sellPrice: 8500,
    quantity: 4,
    profit: 13800,
    profitRate: 76.7,
    platform: 'mercari',
    soldAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
]

export const MOCK_TRENDS: MarketTrend[] = [
  {
    category: 'トレカ・カードゲーム',
    trend: 'rising',
    avgProfitRate: 48.5,
    competitionLevel: 'medium',
    recommendedBrands: ['ポケモン', '遊戯王', 'ワンピース'],
    insight: '限定版や新弾発売直後に需要集中。BOX単位での仕入れが効率的。二次流通価格は定価の1.5〜3倍になることも。',
  },
  {
    category: 'ゲーム機・周辺機器',
    trend: 'stable',
    avgProfitRate: 12.8,
    competitionLevel: 'high',
    recommendedBrands: ['Nintendo', 'Sony PlayStation'],
    insight: '新作発売前後・年末に価格上昇。品薄情報をいち早くキャッチすることが重要。利益率は低めだが安定した需要がある。',
  },
  {
    category: 'LEGO・プラモデル',
    trend: 'rising',
    avgProfitRate: 28.4,
    competitionLevel: 'low',
    recommendedBrands: ['LEGO テクニック', 'バンダイ ガンプラ'],
    insight: '廃番後に価格が上昇するパターンが多い。テクニックシリーズの需要が急上昇中。競合が少なく穴場カテゴリ。',
  },
  {
    category: '高級家電・AV機器',
    trend: 'stable',
    avgProfitRate: 10.5,
    competitionLevel: 'medium',
    recommendedBrands: ['ダイソン', 'Apple', 'ソニー'],
    insight: 'セール品・ポイント還元を活用すると実質利益率が向上。楽天スーパーセール時の仕入れが特に有効。',
  },
  {
    category: 'スニーカー・ストリートファッション',
    trend: 'rising',
    avgProfitRate: 52.0,
    competitionLevel: 'high',
    recommendedBrands: ['Nike', 'New Balance', 'ASICS'],
    insight: '限定コラボは抽選当選後に即2〜3倍に。抽選情報の収集と素早い行動が鍵。サイズによって価格差が大きい。',
  },
]

export const MOCK_DASHBOARD: DashboardStats = {
  totalRevenue: 1245800,
  totalProfit: 187320,
  profitRate: 15.0,
  totalItems: 47,
  pendingApprovals: 3,
  monthlyRevenue: [
    { month: '10月', revenue: 180000, profit: 27000, items: 6 },
    { month: '11月', revenue: 210000, profit: 34000, items: 8 },
    { month: '12月', revenue: 380000, profit: 62000, items: 14 },
    { month: '1月', revenue: 145000, profit: 21000, items: 5 },
    { month: '2月', revenue: 168000, profit: 24000, items: 7 },
    { month: '3月', revenue: 162800, profit: 19320, items: 7 },
  ],
  categoryBreakdown: [
    { category: 'トレカ', revenue: 420000, profit: 85000, count: 18 },
    { category: 'ゲーム', revenue: 310000, profit: 39600, count: 12 },
    { category: 'LEGO', revenue: 215000, profit: 38400, count: 8 },
    { category: '家電', revenue: 300800, profit: 24320, count: 9 },
  ],
}
